import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const HUB_URL=Deno.env.get("SUPABASE_URL")!; const HUB_SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const TV_URL=Deno.env.get("TV_SUPABASE_URL")||"https://gndcgttnpxsjufmehgyi.supabase.co"; const TV_ANON_KEY=Deno.env.get("TV_SUPABASE_ANON_KEY")||"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZGNndHRucHhzanVmbWVoZ3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3MjM5MTMsImV4cCI6MjA5NTI5OTkxM30.N4TQQbIGQfp80iCm8txx72_3XdnJ2HuK6-xQQ1yNJmQ";
const db=createClient(HUB_URL,HUB_SERVICE_KEY); const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"GET, PATCH, OPTIONS","Content-Type":"application/json"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors}); const fail=(m:string,s=400,c?:string)=>json({success:false,error:{message:m,...(c?{code:c}:{})}},s);
async function auth(req:Request){const h=req.headers.get("Authorization")||"";if(!h.toLowerCase().startsWith("bearer ")||!TV_ANON_KEY)return null;const token=h.slice(7).trim();if(!token)return null;const r=await fetch(`${TV_URL}/auth/v1/user`,{headers:{apikey:TV_ANON_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)return null;return await r.json();}
const ADMIN_EMAILS=new Set(["bethelincovibetv@gmail.com","bethelgoodgift3@gmail.com","goodgiftdigital@gmail.com","bethelchukwunyere1@gmail.com"]);
function isAdmin(u:any){return u?.app_metadata?.role==="admin"||u?.app_metadata?.is_admin===true||ADMIN_EMAILS.has(String(u?.email||"").toLowerCase());}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const user=await auth(req);if(!user)return fail("Your session is invalid or expired",401,"INVALID_SESSION");if(!isAdmin(user))return fail("Administrator access required",403,"FORBIDDEN");const url=new URL(req.url);const path=url.pathname.replace(/^.*?(\/api\/)/,"/api/").replace(/\/$/,"");
if(path==="/api/admin/audiences"&&req.method==="GET"){let q=db.from("whatsapp_audiences").select("*").order("created_at",{ascending:false});const status=url.searchParams.get("status"),type=url.searchParams.get("community_type"),category=url.searchParams.get("category_id");if(status&&status!=="all")q=q.eq("verification_status",status);if(type)q=q.eq("community_type",type);if(category)q=q.eq("category_id",category);const{data,error}=await q;if(error)return fail(error.message,500,"DB_ERROR");return json({success:true,data:data||[]});}
const m=path.match(/^\/api\/admin\/audiences\/([^/]+)\/status$/);if(m&&req.method==="PATCH"){let b:any={};try{b=await req.json()}catch{};const action=String(b.action||"");const map:any={submitted_for_review:{verification_status:"under_review",is_published:false},under_review:{verification_status:"under_review",is_published:false},approved:{verification_status:"verified",is_published:true},rejected:{verification_status:"rejected",is_published:false},suspended:{verification_status:"suspended",is_published:false}};if(!map[action])return fail("Invalid verification action",422,"VALIDATION_ERROR");if(action==="rejected"&&!String(b.rejection_reason||"").trim())return fail("A meaningful rejection reason is required",422,"VALIDATION_ERROR");const patch={...map[action],rejection_reason:action==="rejected"?String(b.rejection_reason).trim():null,verified_at:action==="approved"?new Date().toISOString():null,updated_at:new Date().toISOString()};const{data,error}=await db.from("whatsapp_audiences").update(patch).eq("id",m[1]).select("*").single();if(error)return fail(error.message,500,"DB_ERROR");return json({success:true,data});}
return fail("Admin route not found",404,"NOT_FOUND");}catch(e){console.error("Admin API error",e);return fail(e instanceof Error?e.message:"Internal server error",500,"INTERNAL_ERROR");}});