import { supabase } from "@/integrations/supabase/client";
import { whatsappPromotersHub } from "./whatsappPromotersHub";

export type CommunityType = "group" | "channel" | "status_audience";
export type VerificationStatus = "submitted" | "under_review" | "verified" | "rejected" | "suspended";
export interface WhatsAppCommunity { id:string; promoter_id:string; name:string; category_id:string|null; category?:{id:string;name:string;slug:string}|null; community_type:CommunityType; member_count:number; active_daily_views:number; country_primary:string; demographics_summary:string|null; proof_screenshot_url:string; verification_status:VerificationStatus; is_published:boolean; rejection_reason:string|null; verified_at:string|null; created_at:string; updated_at:string; }

export const COMMUNITY_TYPES = [
 {id:"group" as CommunityType,label:"WhatsApp Group",shortLabel:"Group",description:"Interactive chat community with member discussions",sizeLabel:"Member Count",sizePlaceholder:"e.g. 1024",icon:"👥"},
 {id:"channel" as CommunityType,label:"WhatsApp Channel",shortLabel:"Channel",description:"One-way broadcast channel with high subscriber reach",sizeLabel:"Subscriber Count",sizePlaceholder:"e.g. 5500",icon:"📢"},
 {id:"status_audience" as CommunityType,label:"WhatsApp Status Audience",shortLabel:"Status Audience",description:"Personal contact list delivering high story/status view rates",sizeLabel:"Estimated Audience Size",sizePlaceholder:"e.g. 2500",icon:"📱"},
] as const;
export const DEFAULT_COMMUNITY_CATEGORIES = [
 {id:"cat-fashion",name:"Fashion & Apparel",slug:"fashion"},{id:"cat-tech",name:"Technology & Gadgets",slug:"tech"},{id:"cat-food",name:"Food, Drinks & Restaurants",slug:"food"},{id:"cat-beauty",name:"Beauty & Personal Care",slug:"beauty"},{id:"cat-business",name:"Business, Finance & Crypto",slug:"business"},{id:"cat-real-estate",name:"Real Estate & Housing",slug:"real-estate"},{id:"cat-education",name:"Education & Jobs",slug:"education"},{id:"cat-entertainment",name:"Entertainment & Events",slug:"entertainment"},{id:"cat-services",name:"Local Services & Trades",slug:"services"},
];
export function canEditCommunity(c:{verification_status?:string;is_published?:boolean},isAdmin=false){if(isAdmin)return{allowed:true};if(c.verification_status==="verified"&&c.is_published)return{allowed:false,reason:"This audience is verified and cannot be edited directly. Contact an administrator if important information needs to be changed."};if(c.verification_status==="suspended")return{allowed:false,reason:"This audience has been suspended and cannot be edited."};return{allowed:true};}
export function validateCommunityInput(p:{name:string;communityType:CommunityType;memberCount:number;activeDailyViews?:number}){if(!p.name?.trim())return{isValid:false,error:"Community name is required."};if(!["group","channel","status_audience"].includes(p.communityType))return{isValid:false,error:"Invalid community type selected."};if(!Number.isFinite(p.memberCount)||p.memberCount<=0)return{isValid:false,error:"Audience / member count must be greater than zero."};if(p.activeDailyViews!==undefined&&(!Number.isFinite(p.activeDailyViews)||p.activeDailyViews<0))return{isValid:false,error:"Active daily views cannot be negative."};return{isValid:true};}

const PROOF_UPLOAD_URL = "https://xdfulgwlhqvwpntzbgeq.supabase.co/functions/v1/promoter-proof-upload";
export async function uploadCommunityProofScreenshot(file:File,promoterId:string):Promise<string>{
  if(!file)throw new Error("No image file provided for upload.");
  if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type))throw new Error("Invalid image format. Supported formats: JPG, PNG, WEBP, GIF.");
  if(file.size>10*1024*1024)throw new Error("Screenshot image size exceeds 10MB limit.");
  const upload=async(token:string)=>{const form=new FormData();form.append("file",file,file.name);form.append("promoter_id",promoterId);const response=await fetch(PROOF_UPLOAD_URL,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});let payload:any=null;try{payload=await response.json();}catch{throw new Error(`Proof upload failed (HTTP ${response.status}).`);}if(!response.ok||payload?.success===false){const error:any=new Error(payload?.error?.message||`Proof upload failed (HTTP ${response.status}).`);error.status=response.status;throw error;}return String(payload?.data?.url||"");};
  let {data}=await supabase.auth.getSession();if(!data.session?.access_token)throw new Error("You must be signed in to upload audience proof.");
  try{return await upload(data.session.access_token);}catch(error:any){if(error?.status!==401)throw error;const refreshed=await supabase.auth.refreshSession();const token=refreshed.data.session?.access_token;if(!token)throw new Error("Your session has expired. Please sign in again.");return await upload(token);}
}

export async function getMyCommunities(_promoterId:string){return(await whatsappPromotersHub.audiences()) as WhatsAppCommunity[];}
export async function getCommunityById(id:string):Promise<WhatsAppCommunity|null>{if(!id)return null;try{return await whatsappPromotersHub.getAudience(id) as WhatsAppCommunity;}catch(e){if(e instanceof Error&&/not found/i.test(e.message))return null;throw new Error(`Failed to load WhatsApp audience: ${e instanceof Error?e.message:String(e)}`);}}
export async function createCommunity(p:{promoterId:string;name:string;categoryId?:string|null;communityType:CommunityType;memberCount:number;activeDailyViews?:number;countryPrimary?:string;demographicsSummary?:string|null;proofScreenshotUrl:string}){const v=validateCommunityInput({name:p.name,communityType:p.communityType,memberCount:p.memberCount,activeDailyViews:p.activeDailyViews});if(!v.isValid)throw new Error(v.error);if(!p.proofScreenshotUrl)throw new Error("Audience proof screenshot is mandatory for verification.");return await whatsappPromotersHub.createAudience({name:p.name.trim(),category_id:p.categoryId||null,community_type:p.communityType,member_count:Math.floor(p.memberCount),active_daily_views:Math.floor(p.activeDailyViews||0),country_primary:p.countryPrimary?.trim()||"Nigeria",demographics_summary:p.demographicsSummary?.trim()||null,proof_screenshot_url:p.proofScreenshotUrl}) as WhatsAppCommunity;}
export async function updateCommunity(p:{communityId:string;name:string;categoryId?:string|null;communityType:CommunityType;memberCount:number;activeDailyViews?:number;countryPrimary?:string;demographicsSummary?:string|null;proofScreenshotUrl?:string;isAdmin?:boolean}){const v=validateCommunityInput({name:p.name,communityType:p.communityType,memberCount:p.memberCount,activeDailyViews:p.activeDailyViews});if(!v.isValid)throw new Error(v.error);return await whatsappPromotersHub.updateAudience(p.communityId,{name:p.name.trim(),category_id:p.categoryId||null,community_type:p.communityType,member_count:Math.floor(p.memberCount),active_daily_views:Math.floor(p.activeDailyViews||0),country_primary:p.countryPrimary?.trim()||"Nigeria",demographics_summary:p.demographicsSummary?.trim()||null,...(p.proofScreenshotUrl?{proof_screenshot_url:p.proofScreenshotUrl}:{})}) as WhatsAppCommunity;}
export async function deleteCommunity(id:string){await whatsappPromotersHub.deleteAudience(id);}
export async function getCommunityCategories(){return DEFAULT_COMMUNITY_CATEGORIES;}
export async function getPublicVerifiedCommunities(filters?:{categoryId?:string;communityType?:CommunityType;country?:string;minMembers?:number}){return await whatsappPromotersHub.publicAudiences({category_id:filters?.categoryId,community_type:filters?.communityType,country:filters?.country,min_members:filters?.minMembers}) as WhatsAppCommunity[];}
