import { supabase } from "@/integrations/supabase/client";

export interface NetworkMember { id:string; name:string; businessName:string; category:string; location:string; phone:string; email?:string; statusViewsEstimate:number; verified:boolean; openForAds:boolean; ratePerPost?:number; bundlePrice?:number; bio:string; avatarUrl?:string; joinedAt:string; }
export interface ConnectionLog { id:string; contactId:string; contactName:string; businessName:string; category:string; phone:string; syncedAt:string; method:"google_api"|"vcf_export"; googleResourceName?:string; mutualConfirmed:boolean; }
export interface StatusAdBooking { id:string; creatorId:string; creatorName:string; advertiserId:string; advertiserName:string; advertiserPhone:string; advertiserEmail?:string; campaignTitle:string; caption:string; mediaUrl?:string; targetDate:string; slotCount:number; totalAmount:number; status:"pending"|"accepted"|"declined"|"posted_with_proof"|"completed"; proofScreenshotUrl?:string; proofSubmittedAt?:string; proofViewerCount?:number; notes?:string; createdAt:string; }
export interface UserEnginePreferences { autoExchangeEnabled:boolean; isPaused:boolean; targetCategories:string[]; targetLocations:string[]; openForAds:boolean; ratePerPost:number; bundlePrice:number; audienceNiche:string; estimatedViews:number; customWhatsAppNumber:string; }

export const BUSINESS_CATEGORIES=["All Categories","Tech & Electronics","Fashion & Apparel","Food & Catering","Events & Entertainment","Solar & Energy","Media & Photography","Logistics & Transport","Beauty & Wellness","Real Estate & Property","Professional Services","Automotive & Spare Parts"];
export const LAGOS_LOCATIONS=["All Lagos Locations","Computer Village, Ikeja","Ikeja / Maryland","Lekki Phase 1 & 2","Victoria Island","Ikoyi","Yaba / Akoka","Surulere","Alaba International, Ojo","Trade Fair Complex","Balogun / Idumota","Gbagada / Ogudu","Ikorodu","Festac Town","Ajah / Sangotedo"];
export const DEFAULT_PREFERENCES:UserEnginePreferences={autoExchangeEnabled:true,isPaused:false,targetCategories:["All Categories"],targetLocations:["All Lagos Locations"],openForAds:false,ratePerPost:0,bundlePrice:0,audienceNiche:"",estimatedViews:0,customWhatsAppNumber:""};
/** Compatibility export only. Production members come from verified/published Supabase communities. */
export const INITIAL_VERIFIED_POOL:NetworkMember[]=[];

let connectionCache:ConnectionLog[]=[];
let bookingCache:StatusAdBooking[]=[];
let preferenceCache:UserEnginePreferences=DEFAULT_PREFERENCES;
let networkCache:NetworkMember[]=[];

function mapNetwork(rows:any[]):NetworkMember[]{return (rows??[]).flatMap((r:any)=>{const p=Array.isArray(r.promoter)?r.promoter[0]:r.promoter;const c=Array.isArray(r.category)?r.category[0]:r.category;if(!p||p.status!=="active"||!p.is_verified)return[];return[{id:r.id,name:p.display_name,businessName:r.name,category:c?.name??p.niche?.[0]??"Business",location:"Nigeria",phone:p.phone_whatsapp,statusViewsEstimate:r.active_daily_views??0,verified:true,openForAds:false,bio:p.bio??"",joinedAt:r.created_at}];});}

export async function refreshVerifiedNetworkMembers():Promise<NetworkMember[]>{const {data,error}=await supabase.from("whatsapp_communities").select("id,name,active_daily_views,created_at,promoter:promoter_profiles(id,display_name,phone_whatsapp,bio,niche,is_verified,status),category:categories(name)").eq("verification_status","verified").eq("is_published",true).order("active_daily_views",{ascending:false});if(error)throw error;networkCache=mapNetwork(data??[]);return networkCache;}
export function getVerifiedNetworkMembers():NetworkMember[]{return networkCache;}

function mapLog(r:any):ConnectionLog{return{id:r.id,contactId:r.contact_id,contactName:r.contact_name,businessName:r.business_name,category:r.category,phone:r.phone,syncedAt:r.synced_at,method:r.method,googleResourceName:r.google_resource_name??undefined,mutualConfirmed:r.mutual_confirmed};}
function mapBooking(r:any):StatusAdBooking{return{id:r.id,creatorId:r.creator_id,creatorName:r.creator_name,advertiserId:r.advertiser_id,advertiserName:r.advertiser_name,advertiserPhone:r.advertiser_phone,advertiserEmail:r.advertiser_email??undefined,campaignTitle:r.campaign_title,caption:r.caption,mediaUrl:r.media_url??undefined,targetDate:r.target_date,slotCount:r.slot_count,totalAmount:r.total_amount,status:r.status,proofScreenshotUrl:r.proof_screenshot_url??undefined,proofSubmittedAt:r.proof_submitted_at??undefined,proofViewerCount:r.proof_viewer_count??undefined,notes:r.notes??undefined,createdAt:r.created_at};}

export function getConnectionLogs():ConnectionLog[]{return connectionCache;}
export function recordConnectionLog(log:Omit<ConnectionLog,"id"|"syncedAt">):ConnectionLog{const entry:ConnectionLog={...log,id:`pending_${Date.now()}`,syncedAt:new Date().toISOString()};connectionCache=[entry,...connectionCache.filter(x=>x.contactId!==log.contactId)];void (async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user)return;const {data,error}=await supabase.from("whatsapp_engine_connection_logs").upsert({user_id:user.id,contact_id:log.contactId,contact_name:log.contactName,business_name:log.businessName,category:log.category,phone:log.phone,method:log.method,google_resource_name:log.googleResourceName??null,mutual_confirmed:log.mutualConfirmed},{onConflict:"user_id,contact_id"}).select().single();if(error){console.error("Failed to persist connection log",error);return;}connectionCache=[mapLog(data),...connectionCache.filter(x=>x.contactId!==log.contactId)];})();return entry;}
export function isContactConnected(contactId:string):boolean{return connectionCache.some(x=>x.contactId===contactId);}

export function getUserEnginePreferences():UserEnginePreferences{return preferenceCache;}
export function saveUserEnginePreferences(prefs:UserEnginePreferences):void{preferenceCache=prefs;void (async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user)return;const {error}=await supabase.from("whatsapp_engine_preferences").upsert({user_id:user.id,auto_exchange_enabled:prefs.autoExchangeEnabled,is_paused:prefs.isPaused,target_categories:prefs.targetCategories,target_locations:prefs.targetLocations,open_for_ads:prefs.openForAds,rate_per_post:prefs.ratePerPost,bundle_price:prefs.bundlePrice,audience_niche:prefs.audienceNiche,estimated_views:prefs.estimatedViews,custom_whatsapp_number:prefs.customWhatsAppNumber});if(error)console.error("Failed to persist engine preferences",error);})();}

export function getStatusAdBookings():StatusAdBooking[]{return bookingCache;}
export function createStatusAdBooking(booking:Omit<StatusAdBooking,"id"|"createdAt"|"status">):StatusAdBooking{const entry:StatusAdBooking={...booking,id:`pending_${Date.now()}`,status:"pending",createdAt:new Date().toISOString()};bookingCache=[entry,...bookingCache];void (async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user)return;let creatorUserId:string|undefined;const {data:community,error:communityError}=await supabase.from("whatsapp_communities").select("promoter:promoter_profiles(user_id)").eq("id",booking.creatorId).maybeSingle();if(communityError){console.error("Failed to resolve booking creator",communityError);return;}const promoter=Array.isArray((community as any)?.promoter)?(community as any).promoter[0]:(community as any)?.promoter;creatorUserId=promoter?.user_id;if(!creatorUserId){console.error("Booking creator is not a verified community");return;}const {data,error}=await supabase.from("whatsapp_status_ad_bookings").insert({creator_id:creatorUserId,advertiser_id:user.id,creator_name:booking.creatorName,advertiser_name:booking.advertiserName,advertiser_phone:booking.advertiserPhone,advertiser_email:booking.advertiserEmail??null,campaign_title:booking.campaignTitle,caption:booking.caption,media_url:booking.mediaUrl??null,target_date:booking.targetDate,slot_count:booking.slotCount,total_amount:booking.totalAmount,status:"pending"}).select().single();if(error){console.error("Failed to persist status ad booking",error);return;}bookingCache=[mapBooking(data),...bookingCache.filter(x=>x.id!==entry.id)];})();return entry;}
export function updateBookingStatus(bookingId:string,update:Partial<StatusAdBooking>):StatusAdBooking[]{const i=bookingCache.findIndex(b=>b.id===bookingId);if(i>=0)bookingCache[i]={...bookingCache[i],...update};const patch:any={};if(update.status!==undefined)patch.status=update.status;if(update.proofScreenshotUrl!==undefined)patch.proof_screenshot_url=update.proofScreenshotUrl;if(update.proofSubmittedAt!==undefined)patch.proof_submitted_at=update.proofSubmittedAt;if(update.proofViewerCount!==undefined)patch.proof_viewer_count=update.proofViewerCount;if(update.notes!==undefined)patch.notes=update.notes;void supabase.from("whatsapp_status_ad_bookings").update(patch).eq("id",bookingId).then(({error})=>{if(error)console.error("Failed to persist booking update",error);});return bookingCache;}
export function clearAllEngineData():void{connectionCache=[];preferenceCache=DEFAULT_PREFERENCES;void (async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user)return;await Promise.all([supabase.from("whatsapp_engine_connection_logs").delete().eq("user_id",user.id),supabase.from("whatsapp_engine_preferences").delete().eq("user_id",user.id)]);})();}

void refreshVerifiedNetworkMembers().catch(()=>{ /* Empty network is intentional until Supabase returns verified published communities. */ });
void (async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user)return;const [logs,prefs,bookings]=await Promise.all([supabase.from("whatsapp_engine_connection_logs").select("*").order("synced_at",{ascending:false}),supabase.from("whatsapp_engine_preferences").select("*").eq("user_id",user.id).maybeSingle(),supabase.from("whatsapp_status_ad_bookings").select("*").or(`creator_id.eq.${user.id},advertiser_id.eq.${user.id}`).order("created_at",{ascending:false})]);if(!logs.error)connectionCache=(logs.data??[]).map(mapLog);if(!prefs.error&&prefs.data)preferenceCache={autoExchangeEnabled:prefs.data.auto_exchange_enabled,isPaused:prefs.data.is_paused,targetCategories:prefs.data.target_categories??[],targetLocations:prefs.data.target_locations??[],openForAds:prefs.data.open_for_ads,ratePerPost:prefs.data.rate_per_post,bundlePrice:prefs.data.bundle_price,audienceNiche:prefs.data.audience_niche,estimatedViews:prefs.data.estimated_views,customWhatsAppNumber:prefs.data.custom_whatsapp_number};if(!bookings.error)bookingCache=(bookings.data??[]).map(mapBooking);})();
