import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { CreditCard, Loader2, ShieldCheck, Unplug, CheckCircle2, ExternalLink, ArrowRight, ArrowLeft, Sparkles, Eye, EyeOff, CircleHelp } from "lucide-react";

type Account = { public_key: string | null; merchant_id: string | null; business_name: string | null; status: string; last_verified_at: string | null } | null;
const STEPS = ["Get started", "Set up Paystack", "Connect", "Ready to sell"];

export default function SellerPayments() {
  const { user, loading } = useAuth();
  const [account, setAccount] = useState<Account>(null); const [busy, setBusy] = useState(false); const [checking, setChecking] = useState(true); const [step, setStep] = useState(0); const [showGuide, setShowGuide] = useState(false); const [showSecret, setShowSecret] = useState(false);
  const [form, setForm] = useState({ public_key: "", secret_key: "", merchant_id: "" });
  const load = async () => { setChecking(true); const { data, error } = await supabase.functions.invoke("seller-paystack", { body: { action: "status" } }); if (!error) { setAccount(data?.account ?? null); if (data?.account?.status === "connected") setStep(3); } setChecking(false); };
  useEffect(() => { if (user) load(); }, [user]);
  if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  if (!user) return <Navigate to="/login?redirect=/dashboard/payments" replace />;
  const connect = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setStep(2); const { data, error } = await supabase.functions.invoke("seller-paystack", { body: { action: "connect", ...form } }); setBusy(false); if (error || data?.error) { toast.error(data?.error || "Could not verify those keys. Please check and try again."); setStep(2); await load(); return; } setForm({ public_key: "", secret_key: "", merchant_id: "" }); setAccount(data.account); setStep(3); toast.success("Paystack connected successfully."); };
  const disconnect = async () => { if (!confirm("Disconnect your Paystack account? Buyers will no longer be able to pay you directly.")) return; setBusy(true); await supabase.functions.invoke("seller-paystack", { body: { action: "disconnect" } }); setBusy(false); setAccount(null); setStep(0); toast.success("Disconnected"); };
  const status = account?.status ?? "not_connected"; const masked = (value: string | null) => value ? `${value.slice(0, 8)}••••••••${value.slice(-4)}` : "—";
  return <div className="mx-auto w-full max-w-2xl px-3 py-5 sm:px-4">
    <Helmet><title>Payment Setup — Paystack | Seller Dashboard</title></Helmet>
    <div className="mb-5 flex items-center gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-primary/15 text-primary"><CreditCard className="h-5 w-5" /></span><div className="min-w-0"><h1 className="text-xl font-bold">Payment setup</h1><p className="text-xs text-muted-foreground">Connect your own Paystack account to sell digital products.</p></div></div>
    {status !== "connected" && <div className="mb-5 overflow-hidden rounded-2xl border bg-card p-3"><div className="flex items-center justify-between gap-1">{STEPS.map((label, i) => <div key={label} className="flex min-w-0 flex-1 items-center"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${i <= step ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{i < step ? <CheckCircle2 className="h-4 w-4" /> : i + 1}</div><span className={`ml-1 hidden truncate text-[10px] sm:block ${i === step ? "font-semibold" : "text-muted-foreground"}`}>{label}</span>{i < STEPS.length - 1 && <div className={`mx-1 h-px flex-1 ${i < step ? "bg-primary" : "bg-border"}`} />}</div>)}</div></div>}
    <Card className="overflow-hidden rounded-3xl">
      {step === 0 && status !== "connected" && <><CardHeader><div className="mb-2 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10"><Sparkles className="h-6 w-6 text-primary" /></div><CardTitle>Let’s set up your payments 🪄</CardTitle><CardDescription>Your Paystack account belongs to you. We’ll connect it securely so customers can pay you directly for your digital products.</CardDescription></CardHeader><CardContent><Button className="w-full" onClick={() => setStep(1)}>Get started <ArrowRight className="ml-2 h-4 w-4" /></Button></CardContent></>}
      {step === 1 && status !== "connected" && <><CardHeader><CardTitle>Set up your Paystack business</CardTitle><CardDescription>Follow these simple steps. You do not need to understand anything technical.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="rounded-2xl border bg-muted/30 p-4 text-sm"><ol className="list-decimal space-y-2 pl-5"><li>Open your Paystack Dashboard and sign in.</li><li>Make sure your business/profile is set up and activated for live payments.</li><li>From the Dashboard, open <b>Developers</b> to access your API keys and developer tools. Paystack's new Dashboard places Developers in the sidebar. citeturn0search4</li><li>Open <b>API Keys & Webhooks</b>.</li><li>Under <b>API Configuration - Live Mode</b>, copy your <b>Live Public Key</b> and <b>Live Secret Key</b>. Paystack confirms these are the keys used for live payments. citeturn0search1turn0search0</li></ol></div><Button variant="outline" className="w-full" asChild><a href="https://dashboard.paystack.com/" target="_blank" rel="noreferrer">Open Paystack Dashboard <ExternalLink className="ml-2 h-4 w-4" /></a></Button><div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs"><b>Important:</b> Use your <b>Live</b> keys when you are ready to receive real customer payments. Keep your Secret Key private. Paystack says secret keys must be stored securely. citeturn0search0</div><Button className="w-full" onClick={() => setStep(2)}>I have my keys — continue <ArrowRight className="ml-2 h-4 w-4" /></Button><Button variant="ghost" className="w-full" onClick={() => setStep(0)}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button></CardContent></>}
      {step === 2 && status !== "connected" && <><CardHeader><CardTitle>Connect your Paystack account</CardTitle><CardDescription>Paste the keys you copied from Paystack. We will verify them before saving.</CardDescription></CardHeader><CardContent><form onSubmit={connect} className="space-y-4"><div className="space-y-2"><Label htmlFor="pk">Paystack public key</Label><Input id="pk" required className="w-full min-w-0" placeholder="pk_live_xxxxxxxx" value={form.public_key} onChange={e => setForm({ ...form, public_key: e.target.value })} /><p className="text-[11px] text-muted-foreground">Find it in Paystack → Developers → API Keys & Webhooks → Live Mode. citeturn0search4turn0search1</p></div><div className="space-y-2"><Label htmlFor="sk">Paystack secret key</Label><div className="relative"><Input id="sk" required type={showSecret ? "text" : "password"} className="w-full min-w-0 pr-11" placeholder="sk_live_xxxxxxxx" value={form.secret_key} onChange={e => setForm({ ...form, secret_key: e.target.value })} /><button type="button" aria-label={showSecret ? "Hide secret key" : "Show secret key"} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-muted-foreground" onClick={() => setShowSecret(!showSecret)}>{showSecret ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div><p className="text-[11px] text-muted-foreground">Find it in the same <b>API Keys & Webhooks</b> section. You may need to reveal it with your Paystack account password. citeturn0search1</p></div><div className="space-y-2"><Label htmlFor="mid">Merchant ID <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="mid" className="w-full min-w-0" placeholder="Optional merchant ID" value={form.merchant_id} onChange={e => setForm({ ...form, merchant_id: e.target.value })} /></div><Button type="submit" className="w-full" disabled={busy}>{busy ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Connecting securely…</> : <>Verify & connect <ShieldCheck className="ml-2 h-4 w-4" /></>}</Button><Button type="button" variant="ghost" className="w-full" disabled={busy} onClick={() => setStep(1)}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button></form><button type="button" className="mt-3 flex w-full items-center justify-center gap-1 text-xs text-muted-foreground" onClick={() => setShowGuide(!showGuide)}><CircleHelp className="h-3.5 w-3.5" />Where do I find my keys?</button>{showGuide && <div className="mt-3 rounded-2xl border bg-muted/30 p-3 text-xs leading-5">Paystack Dashboard → <b>Developers</b> → <b>API Keys & Webhooks</b> → <b>API Configuration - Live Mode</b> → copy your Live Public Key and Live Secret Key. citeturn0search4turn0search1</div>}</CardContent></>}
      {step === 3 && status === "connected" && account && <><CardHeader className="text-center"><div className="mx-auto mb-3 flex h-16 w-16 animate-[pulse_1.5s_ease-in-out_1] items-center justify-center rounded-full bg-emerald-500/15"><CheckCircle2 className="h-9 w-9 text-emerald-600" /></div><CardTitle>Paystack Connected! 🎉</CardTitle><CardDescription>Your account is ready to receive payments for your digital products.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="overflow-hidden rounded-2xl border bg-muted/30 p-4 text-sm"><p className="flex items-center gap-2 font-medium text-emerald-600"><ShieldCheck className="h-4 w-4 shrink-0" />Verified with Paystack</p><div className="mt-3 space-y-1 text-xs text-muted-foreground break-words"><p>Business: <span className="font-medium text-foreground">{account.business_name || "Connected account"}</span></p><p className="break-all">Public key: <span className="font-mono">{masked(account.public_key)}</span></p>{account.merchant_id && <p className="break-all">Merchant ID: <span className="font-mono">{account.merchant_id}</span></p>}{account.last_verified_at && <p>Last verified: {new Date(account.last_verified_at).toLocaleString()}</p>}</div></div><div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm"><p className="font-semibold">You're ready to sell 📦</p><p className="mt-1 text-xs text-muted-foreground">Publish your digital products and customers can pay through your connected Paystack account.</p></div><Button className="w-full" onClick={() => window.location.assign("/dashboard/products")}>Go to my products <ArrowRight className="ml-2 h-4 w-4" /></Button><Button variant="outline" className="w-full" onClick={disconnect} disabled={busy}><Unplug className="mr-2 h-4 w-4" />Disconnect Paystack</Button></CardContent></>}
    </Card></div>;
}
