import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import {
  Wand2,
  Sparkles,
  Check,
  Plus,
  Trash2,
  Image as ImageIcon,
  MessageCircle,
  Briefcase,
  Loader2,
  ArrowRight,
  ExternalLink,
  Layers,
  Tag,
  CheckCircle2,
  Pencil,
  Copy,
} from "lucide-react";
import { toast } from "sonner";
import {
  generateSingleServiceWithAI,
  generateServiceCatalogWithAI,
  DesignedService,
} from "@/lib/businessServiceAIEngine";
import ServiceGraphicPickerModal from "./ServiceGraphicPickerModal";

export default function AIServiceDesignerDialog({
  open,
  onOpenChange,
  businessName,
  category,
  cityOrRegion,
  onApplyServices,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  businessName: string;
  category?: string;
  cityOrRegion?: string;
  onApplyServices: (services: any[]) => void;
}) {
  const [mode, setMode] = useState<"single" | "catalog">("single");
  const [conceptInput, setConceptInput] = useState("");
  const [targetAudience, setTargetAudience] = useState("Corporate clients & retail buyers");
  const [generating, setGenerating] = useState(false);

  // Generated state
  const [singleResult, setSingleResult] = useState<DesignedService | null>(null);
  const [catalogResult, setCatalogResult] = useState<DesignedService[]>([]);
  const [catalogHeadline, setCatalogHeadline] = useState("");

  // Graphic Picker State
  const [graphicPickerOpen, setGraphicPickerOpen] = useState(false);
  const [activeGraphicServiceIndex, setActiveGraphicServiceIndex] = useState<number | "single">("single");

  // Step indicator: 'input' -> 'preview_edit'
  const [step, setStep] = useState<"input" | "preview">("input");

  const handleGenerateSingle = async () => {
    if (!conceptInput.trim()) {
      toast.error("Please describe what service you offer (e.g. 'we build websites for small businesses')");
      return;
    }
    setGenerating(true);
    try {
      const res = await generateSingleServiceWithAI({
        businessName,
        category,
        serviceConcept: conceptInput,
        targetAudience,
        cityOrRegion,
      });
      setSingleResult(res);
      setStep("preview");
      toast.success("Professional Service generated by AI!");
    } catch (err: any) {
      toast.error(err.message || "Failed to generate service");
    } finally {
      setGenerating(false);
    }
  };

  const handleGenerateCatalog = async () => {
    setGenerating(true);
    try {
      const res = await generateServiceCatalogWithAI(
        businessName || "Verified Business",
        category || "Professional Services",
        conceptInput || `High quality ${category || "business"} products and services.`
      );
      setCatalogHeadline(res.headline);
      setCatalogResult(res.services);
      setStep("preview");
      toast.success(`Generated ${res.services.length} core services for your catalog!`);
    } catch (err: any) {
      toast.error(err.message || "Failed to generate service suite");
    } finally {
      setGenerating(false);
    }
  };

  const updateSingleField = (field: keyof DesignedService, value: any) => {
    if (!singleResult) return;
    setSingleResult({ ...singleResult, [field]: value });
  };

  const updateCatalogService = (index: number, patch: Partial<DesignedService>) => {
    setCatalogResult((prev) =>
      prev.map((s, i) => (i === index ? { ...s, ...patch } : s))
    );
  };

  const removeCatalogService = (index: number) => {
    setCatalogResult((prev) => prev.filter((_, i) => i !== index));
  };

  const openGraphicPickerFor = (target: number | "single") => {
    setActiveGraphicServiceIndex(target);
    setGraphicPickerOpen(true);
  };

  const handleApplySingle = () => {
    if (!singleResult) return;
    const formatted = {
      title: singleResult.title,
      description: singleResult.description,
      image_url: singleResult.image_url || "",
      link_url: "",
      benefits: singleResult.benefits,
      price: singleResult.suggestedPrice,
      keywords: singleResult.keywords,
      cta_text: singleResult.ctaText,
    };
    onApplyServices([formatted]);
    toast.success(`Added "${singleResult.title}" to your profile!`);
    onOpenChange(false);
  };

  const handleApplyCatalog = (mode: "replace" | "append") => {
    if (catalogResult.length === 0) return;
    const formatted = catalogResult.map((s) => ({
      title: s.title,
      description: s.description,
      image_url: s.image_url || "",
      link_url: "",
      benefits: s.benefits,
      price: s.suggestedPrice,
      keywords: s.keywords,
      cta_text: s.ctaText,
    }));

    onApplyServices(formatted);
    toast.success(`Applied ${catalogResult.length} services to your profile!`);
    onOpenChange(false);
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="max-w-3xl p-0 overflow-hidden rounded-3xl border-primary/30">
          {/* Header */}
          <div className="bg-gradient-to-r from-primary via-indigo-900 to-purple-950 text-white p-6 relative overflow-hidden">
            <div className="relative z-10 space-y-1.5">
              <Badge className="bg-white/20 text-white border-white/30 text-xs font-black px-3 py-1 rounded-full gap-1.5 backdrop-blur-md">
                <Wand2 className="h-3.5 w-3.5" />
                AI SERVICE DESIGNER &amp; COPYWRITER
              </Badge>
              <DialogTitle className="text-xl sm:text-2xl font-bold text-white flex items-center gap-2">
                Create Professional Business Services
              </DialogTitle>
              <DialogDescription className="text-xs sm:text-sm text-white/80 max-w-xl">
                Turn simple concepts like <span className="font-semibold text-white">"we build websites"</span> into high-converting service listings with persuasive benefits, pricing, and visual graphics.
              </DialogDescription>
            </div>
          </div>

          <div className="p-6 space-y-6 max-h-[70vh] overflow-y-auto">
            {step === "input" ? (
              <div className="space-y-5">
                <Tabs value={mode} onValueChange={(v: any) => setMode(v)}>
                  <TabsList className="grid grid-cols-2 bg-muted/60 p-1 rounded-2xl w-full">
                    <TabsTrigger value="single" className="rounded-xl text-xs font-bold gap-1.5">
                      <Briefcase className="h-4 w-4" /> Single Service Generator
                    </TabsTrigger>
                    <TabsTrigger value="catalog" className="rounded-xl text-xs font-bold gap-1.5">
                      <Layers className="h-4 w-4" /> Complete Service Suite
                    </TabsTrigger>
                  </TabsList>

                  {/* Single Service Input Mode */}
                  <TabsContent value="single" className="space-y-4 mt-4">
                    <div className="space-y-2">
                      <Label className="text-xs font-bold text-foreground">
                        What service does your business offer? *
                      </Label>
                      <Textarea
                        rows={3}
                        value={conceptInput}
                        onChange={(e) => setConceptInput(e.target.value)}
                        placeholder="e.g. we build responsive websites and online stores for small businesses with WhatsApp integration and Paystack payment..."
                        className="rounded-xl text-sm"
                      />
                      <p className="text-[11px] text-muted-foreground">
                        Tip: You can type naturally in plain words or bullet points.
                      </p>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 p-4 rounded-2xl bg-muted/30 border">
                      <div>
                        <Label className="text-xs font-bold mb-1 block">Industry / Category</Label>
                        <Input
                          value={category || "General Business"}
                          disabled
                          className="rounded-xl text-xs h-9 bg-muted/50"
                        />
                      </div>
                      <div>
                        <Label className="text-xs font-bold mb-1 block">Target Clients</Label>
                        <Input
                          value={targetAudience}
                          onChange={(e) => setTargetAudience(e.target.value)}
                          placeholder="e.g. Small business owners, scaling brands"
                          className="rounded-xl text-xs h-9"
                        />
                      </div>
                    </div>

                    {/* Quick Example Chips */}
                    <div className="space-y-1.5">
                      <p className="text-xs font-semibold text-muted-foreground">Quick Inspiration Examples:</p>
                      <div className="flex flex-wrap gap-1.5">
                        {[
                          "we build custom ecommerce websites with Paystack",
                          "solar inverter installation and maintenance in Lagos",
                          "bespoke native tailoring and luxury agbada design",
                          "corporate CAC company registration and tax filing",
                          "same-day dispatch delivery and logistics",
                          "professional product photography and video reels",
                        ].map((eg, i) => (
                          <button
                            key={i}
                            type="button"
                            onClick={() => setConceptInput(eg)}
                            className="text-[11px] px-2.5 py-1 rounded-full border bg-card hover:bg-primary/10 hover:text-primary hover:border-primary/40 transition font-medium"
                          >
                            + {eg}
                          </button>
                        ))}
                      </div>
                    </div>

                    <Button
                      onClick={handleGenerateSingle}
                      disabled={generating || !conceptInput.trim()}
                      className="w-full font-bold rounded-xl py-6 gap-2 text-sm shadow-md bg-gradient-to-r from-primary via-indigo-600 to-purple-600 hover:opacity-95"
                    >
                      {generating ? (
                        <>
                          <Loader2 className="h-4 w-4 animate-spin" /> Designing Service With AI...
                        </>
                      ) : (
                        <>
                          <Sparkles className="h-4 w-4" /> Generate Professional Service
                        </>
                      )}
                    </Button>
                  </TabsContent>

                  {/* Complete Catalog Generator */}
                  <TabsContent value="catalog" className="space-y-4 mt-4">
                    <div className="p-4 rounded-2xl bg-primary/5 border border-primary/20 space-y-2">
                      <h4 className="text-sm font-bold flex items-center gap-1.5 text-primary">
                        <Layers className="h-4 w-4" /> 1-Click Complete Service Catalog
                      </h4>
                      <p className="text-xs text-muted-foreground leading-relaxed">
                        AI will analyze your business name (<span className="font-semibold text-foreground">{businessName || "Your Business"}</span>) and category (<span className="font-semibold text-foreground">{category || "General"}</span>) to generate a comprehensive 3 to 4 service suite with descriptions, benefit bullets, and suggested graphics.
                      </p>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-xs font-bold text-foreground">
                        Additional Business Context (Optional)
                      </Label>
                      <Textarea
                        rows={2}
                        value={conceptInput}
                        onChange={(e) => setConceptInput(e.target.value)}
                        placeholder="e.g. Specializes in luxury residential solar setups, 24-hour battery maintenance, and commercial energy audits in Lagos..."
                        className="rounded-xl text-sm"
                      />
                    </div>

                    <Button
                      onClick={handleGenerateCatalog}
                      disabled={generating}
                      className="w-full font-bold rounded-xl py-6 gap-2 text-sm shadow-md bg-gradient-to-r from-primary via-indigo-600 to-purple-600 hover:opacity-95"
                    >
                      {generating ? (
                        <>
                          <Loader2 className="h-4 w-4 animate-spin" /> Generating Full Service Suite...
                        </>
                      ) : (
                        <>
                          <Sparkles className="h-4 w-4" /> Generate 3-4 Complete Services
                        </>
                      )}
                    </Button>
                  </TabsContent>
                </Tabs>
              </div>
            ) : (
              /* Step 2: PREVIEW, EDIT & GRAPHIC ATTACHMENT */
              <div className="space-y-6">
                <div className="flex items-center justify-between border-b pb-3">
                  <div>
                    <h3 className="text-base font-bold flex items-center gap-2">
                      <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                      Generated Service Preview &amp; Editor
                    </h3>
                    <p className="text-xs text-muted-foreground">
                      Review, polish copy, attach stock graphics, and apply directly to your profile.
                    </p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setStep("input")}
                    className="rounded-xl text-xs font-bold"
                  >
                    ← Edit Prompt
                  </Button>
                </div>

                {/* Single Service Preview */}
                {singleResult && mode === "single" && (
                  <div className="space-y-5">
                    {/* Live Visual Card Preview */}
                    <div className="rounded-2xl border bg-card overflow-hidden shadow-lg border-primary/30">
                      <div className="relative aspect-[21/9] sm:aspect-[21/8] bg-muted overflow-hidden">
                        {singleResult.image_url ? (
                          <img
                            src={singleResult.image_url}
                            alt={singleResult.title}
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <div className="w-full h-full bg-gradient-to-br from-primary/20 via-indigo-500/20 to-purple-500/20 flex flex-col items-center justify-center p-4 text-center">
                            <ImageIcon className="h-8 w-8 text-primary/60 mb-1" />
                            <p className="text-xs font-medium text-muted-foreground">No Graphic Attached Yet</p>
                          </div>
                        )}
                        <Button
                          size="sm"
                          onClick={() => openGraphicPickerFor("single")}
                          className="absolute bottom-3 right-3 rounded-xl text-xs font-bold shadow-md bg-black/70 hover:bg-black text-white gap-1.5 backdrop-blur-md"
                        >
                          <ImageIcon className="h-3.5 w-3.5" />
                          {singleResult.image_url ? "Change Graphic" : "Attach AI Graphic / Photo"}
                        </Button>
                      </div>

                      <div className="p-5 space-y-4">
                        <div>
                          <Label className="text-xs font-bold text-muted-foreground">Service Name</Label>
                          <Input
                            value={singleResult.title}
                            onChange={(e) => updateSingleField("title", e.target.value)}
                            className="text-base font-bold rounded-xl mt-1 h-10"
                          />
                        </div>

                        <div>
                          <Label className="text-xs font-bold text-muted-foreground">Persuasive Description</Label>
                          <Textarea
                            rows={3}
                            value={singleResult.description}
                            onChange={(e) => updateSingleField("description", e.target.value)}
                            className="rounded-xl text-xs mt-1 leading-relaxed"
                          />
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          <div>
                            <Label className="text-xs font-bold text-muted-foreground">Pricing Guidance</Label>
                            <Input
                              value={singleResult.suggestedPrice || ""}
                              onChange={(e) => updateSingleField("suggestedPrice", e.target.value)}
                              placeholder="e.g. From ₦85,000"
                              className="rounded-xl text-xs mt-1 h-9"
                            />
                          </div>
                          <div>
                            <Label className="text-xs font-bold text-muted-foreground">Action Button Hook</Label>
                            <Input
                              value={singleResult.ctaText || "Inquire on WhatsApp"}
                              onChange={(e) => updateSingleField("ctaText", e.target.value)}
                              className="rounded-xl text-xs mt-1 h-9"
                            />
                          </div>
                        </div>

                        {/* Benefits list */}
                        <div className="space-y-2 pt-2 border-t">
                          <Label className="text-xs font-bold flex items-center gap-1.5 text-foreground">
                            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> Key Benefits &amp; Deliverables
                          </Label>
                          <div className="space-y-1.5">
                            {singleResult.benefits.map((b, idx) => (
                              <div key={idx} className="flex items-center gap-2">
                                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 shrink-0" />
                                <Input
                                  value={b}
                                  onChange={(e) => {
                                    const next = [...singleResult.benefits];
                                    next[idx] = e.target.value;
                                    updateSingleField("benefits", next);
                                  }}
                                  className="text-xs rounded-xl h-8 flex-1"
                                />
                                <button
                                  type="button"
                                  onClick={() => {
                                    updateSingleField(
                                      "benefits",
                                      singleResult.benefits.filter((_, i) => i !== idx)
                                    );
                                  }}
                                  className="text-muted-foreground hover:text-destructive p-1"
                                >
                                  <Trash2 className="h-3.5 w-3.5" />
                                </button>
                              </div>
                            ))}
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() =>
                                updateSingleField("benefits", [
                                  ...singleResult.benefits,
                                  "New Deliverable or Quality Guarantee",
                                ])
                              }
                              className="text-xs text-primary font-bold h-7 px-2"
                            >
                              + Add Benefit Item
                            </Button>
                          </div>
                        </div>

                        {/* Keywords Tagging */}
                        {singleResult.keywords.length > 0 && (
                          <div className="flex flex-wrap items-center gap-1.5 pt-2">
                            <span className="text-[11px] font-semibold text-muted-foreground flex items-center gap-1">
                              <Tag className="h-3 w-3" /> Search Tags:
                            </span>
                            {singleResult.keywords.map((kw, i) => (
                              <Badge key={i} variant="secondary" className="text-[10px] rounded-md font-medium">
                                #{kw}
                              </Badge>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>

                    <div className="flex flex-col sm:flex-row items-center gap-3 pt-2">
                      <Button
                        onClick={handleApplySingle}
                        className="w-full font-bold rounded-xl py-6 gap-2 text-sm shadow-md bg-emerald-600 hover:bg-emerald-700 text-white"
                      >
                        <Check className="h-4 w-4" /> Apply Service to Profile
                      </Button>
                    </div>
                  </div>
                )}

                {/* Catalog Suite Preview */}
                {catalogResult.length > 0 && mode === "catalog" && (
                  <div className="space-y-4">
                    {catalogHeadline && (
                      <div className="p-3 bg-muted/40 rounded-xl border">
                        <p className="text-xs font-bold text-primary">{catalogHeadline}</p>
                      </div>
                    )}

                    <div className="space-y-4">
                      {catalogResult.map((svc, idx) => (
                        <div key={idx} className="p-4 rounded-2xl border bg-card shadow-xs space-y-3">
                          <div className="flex items-start justify-between gap-3">
                            <div className="flex-1 space-y-1">
                              <div className="flex items-center gap-2">
                                <Badge className="bg-primary/10 text-primary text-[10px] font-bold">
                                  Service {idx + 1}
                                </Badge>
                                <Input
                                  value={svc.title}
                                  onChange={(e) => updateCatalogService(idx, { title: e.target.value })}
                                  className="font-bold text-sm h-8 rounded-lg flex-1"
                                />
                              </div>
                              <Textarea
                                rows={2}
                                value={svc.description}
                                onChange={(e) => updateCatalogService(idx, { description: e.target.value })}
                                className="text-xs rounded-xl mt-1.5"
                              />
                            </div>

                            {/* Service thumbnail */}
                            <div
                              onClick={() => openGraphicPickerFor(idx)}
                              className="h-20 w-24 rounded-xl border bg-muted shrink-0 overflow-hidden cursor-pointer relative group flex items-center justify-center"
                            >
                              {svc.image_url ? (
                                <img src={svc.image_url} alt="" className="w-full h-full object-cover" />
                              ) : (
                                <div className="text-center p-1">
                                  <ImageIcon className="h-5 w-5 mx-auto text-muted-foreground" />
                                  <span className="text-[9px] text-muted-foreground font-bold">Add Visual</span>
                                </div>
                              )}
                              <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition flex items-center justify-center text-white text-[10px] font-bold">
                                Edit
                              </div>
                            </div>
                          </div>

                          <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t text-xs">
                            <div className="flex items-center gap-2">
                              <span className="font-semibold text-muted-foreground text-[11px]">Price:</span>
                              <Input
                                value={svc.suggestedPrice || ""}
                                onChange={(e) => updateCatalogService(idx, { suggestedPrice: e.target.value })}
                                className="h-7 w-32 text-xs rounded-md"
                              />
                            </div>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => removeCatalogService(idx)}
                              className="text-destructive h-7 text-xs px-2 hover:bg-destructive/10"
                            >
                              <Trash2 className="h-3.5 w-3.5 mr-1" /> Remove
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>

                    <div className="pt-3 flex flex-col sm:flex-row gap-3">
                      <Button
                        onClick={() => handleApplyCatalog("append")}
                        className="w-full font-bold rounded-xl py-6 gap-2 text-sm shadow-md bg-emerald-600 hover:bg-emerald-700 text-white"
                      >
                        <Check className="h-4 w-4" /> Apply All {catalogResult.length} Services to Profile
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>

      {/* Embedded Graphic Picker Modal */}
      <ServiceGraphicPickerModal
        open={graphicPickerOpen}
        onOpenChange={setGraphicPickerOpen}
        serviceTitle={
          activeGraphicServiceIndex === "single"
            ? singleResult?.title || "Service"
            : catalogResult[activeGraphicServiceIndex]?.title || "Service"
        }
        categoryHint={category}
        currentImageUrl={
          activeGraphicServiceIndex === "single"
            ? singleResult?.image_url
            : catalogResult[activeGraphicServiceIndex as number]?.image_url
        }
        onSelectImage={(url) => {
          if (activeGraphicServiceIndex === "single") {
            updateSingleField("image_url", url);
          } else {
            updateCatalogService(activeGraphicServiceIndex as number, { image_url: url });
          }
        }}
      />
    </>
  );
}
